#############################################################################
# Makefile for building: cueplayer
# Generated by qmake (2.01a) (Qt 4.5.2) on: ?? ????. 30 02:05:22 2009
# Project:  cueplayer.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile cueplayer.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -march=core2 -O3 -pipe -fomit-frame-pointer -pthread -I/usr/include/gstreamer-0.10 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/libxml2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -march=core2 -O3 -pipe -fomit-frame-pointer -pthread -I/usr/include/gstreamer-0.10 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/libxml2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib64/qt4 -pthread -lgstreamer-0.10 -lgmodule-2.0 -lxml2 -lQtGui -L/usr/lib64 -L/usr/lib64/qt4 -L/usr/X11R6/lib -pthread -lpng -lfreetype -lgobject-2.0 -lSM -lICE -pthread -pthread -lXrender -lXrandr -lfontconfig -lXext -lX11 -lQtCore -lz -lm -pthread -lgthread-2.0 -lrt -lglib-2.0 -ldl -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = cueplayer.cpp \
		main.cpp \
		cueparser.cpp \
		transcoder.cpp \
		apetoflac.cpp moc_cueplayer.cpp \
		moc_transcoder.cpp \
		moc_apetoflac.cpp \
		qrc_ressources.cpp
OBJECTS       = cueplayer.o \
		main.o \
		cueparser.o \
		transcoder.o \
		apetoflac.o \
		moc_cueplayer.o \
		moc_transcoder.o \
		moc_apetoflac.o \
		qrc_ressources.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		cueplayer.pro
QMAKE_TARGET  = cueplayer
DESTDIR       = 
TARGET        = cueplayer

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_cueplayer.h ui_transcoder.h ui_apetoflacdialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: cueplayer.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib64/qt4/libQtGui.prl \
		/usr/lib64/qt4/libQtCore.prl
	$(QMAKE) -unix -o Makefile cueplayer.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/link_pkgconfig.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib64/qt4/libQtGui.prl:
/usr/lib64/qt4/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile cueplayer.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/cueplayer1.0.0 || $(MKDIR) .tmp/cueplayer1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/cueplayer1.0.0/ && $(COPY_FILE) --parents cueplayer.h cueparser.h transcoder.h apetoflac.h .tmp/cueplayer1.0.0/ && $(COPY_FILE) --parents ressources.qrc .tmp/cueplayer1.0.0/ && $(COPY_FILE) --parents cueplayer.cpp main.cpp cueparser.cpp transcoder.cpp apetoflac.cpp .tmp/cueplayer1.0.0/ && $(COPY_FILE) --parents ui/cueplayer.ui ui/transcoder.ui ui/apetoflacdialog.ui .tmp/cueplayer1.0.0/ && (cd `dirname .tmp/cueplayer1.0.0` && $(TAR) cueplayer1.0.0.tar cueplayer1.0.0 && $(COMPRESS) cueplayer1.0.0.tar) && $(MOVE) `dirname .tmp/cueplayer1.0.0`/cueplayer1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/cueplayer1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_cueplayer.cpp moc_transcoder.cpp moc_apetoflac.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_cueplayer.cpp moc_transcoder.cpp moc_apetoflac.cpp
moc_cueplayer.cpp: ui_cueplayer.h \
		cueparser.h \
		transcoder.h \
		ui_transcoder.h \
		apetoflac.h \
		ui_apetoflacdialog.h \
		cueplayer.h
	/usr/bin/moc $(DEFINES) $(INCPATH) cueplayer.h -o moc_cueplayer.cpp

moc_transcoder.cpp: ui_transcoder.h \
		cueparser.h \
		transcoder.h
	/usr/bin/moc $(DEFINES) $(INCPATH) transcoder.h -o moc_transcoder.cpp

moc_apetoflac.cpp: ui_apetoflacdialog.h \
		apetoflac.h
	/usr/bin/moc $(DEFINES) $(INCPATH) apetoflac.h -o moc_apetoflac.cpp

compiler_rcc_make_all: qrc_ressources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_ressources.cpp
qrc_ressources.cpp: ressources.qrc \
		images/convertor.png \
		images/stop.png \
		images/help-about.png \
		images/next.png \
		images/hint.png \
		images/prev.png \
		images/fileopen.png \
		images/play.png \
		images/application-exit.png \
		images/format-indent-more.png \
		images/knotify.png \
		images/pause.png \
		images/format-list-unordered.png
	/usr/bin/rcc -name ressources ressources.qrc -o qrc_ressources.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_cueplayer.h ui_transcoder.h ui_apetoflacdialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_cueplayer.h ui_transcoder.h ui_apetoflacdialog.h
ui_cueplayer.h: ui/cueplayer.ui
	/usr/bin/uic ui/cueplayer.ui -o ui_cueplayer.h

ui_transcoder.h: ui/transcoder.ui
	/usr/bin/uic ui/transcoder.ui -o ui_transcoder.h

ui_apetoflacdialog.h: ui/apetoflacdialog.ui
	/usr/bin/uic ui/apetoflacdialog.ui -o ui_apetoflacdialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

cueplayer.o: cueplayer.cpp cueplayer.h \
		ui_cueplayer.h \
		cueparser.h \
		transcoder.h \
		ui_transcoder.h \
		apetoflac.h \
		ui_apetoflacdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cueplayer.o cueplayer.cpp

main.o: main.cpp cueplayer.h \
		ui_cueplayer.h \
		cueparser.h \
		transcoder.h \
		ui_transcoder.h \
		apetoflac.h \
		ui_apetoflacdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

cueparser.o: cueparser.cpp cueparser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cueparser.o cueparser.cpp

transcoder.o: transcoder.cpp transcoder.h \
		ui_transcoder.h \
		cueparser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o transcoder.o transcoder.cpp

apetoflac.o: apetoflac.cpp apetoflac.h \
		ui_apetoflacdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o apetoflac.o apetoflac.cpp

moc_cueplayer.o: moc_cueplayer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cueplayer.o moc_cueplayer.cpp

moc_transcoder.o: moc_transcoder.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_transcoder.o moc_transcoder.cpp

moc_apetoflac.o: moc_apetoflac.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_apetoflac.o moc_apetoflac.cpp

qrc_ressources.o: qrc_ressources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_ressources.o qrc_ressources.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

